function cfg = default_simulateur_config()
% Configuration par défaut du simulateur physique.

cfg = struct();

cfg.beam = struct( ...
    'L', 0.18, ...                 % m
    'b', 0.02, ...                 % m
    'h', 1.2e-3, ...               % m
    'E', 2.10e11, ...              % Pa
    'rho', 7850, ...               % kg/m^3
    'c', 0.08, ...                 % N.s/m
    'base', 0.0, ...               % m
    'plateauDistance', 0.12);      % m

cfg.mass = struct( ...
    'tipMass', 0.0, ...            % kg
    'startTime', 1.0);             % s

cfg.force = struct( ...
    'value', 0.0, ...              % N
    'enableCompensation', false);

cfg.control = struct( ...
    'positionSetpoint', 0.0, ...   % m
    'currentSetpoint', 0.0, ...    % A
    'positionPID', struct('Kp', 1.0, 'Ki', 0.0, 'Kd', 0.0), ...
    'currentPID', struct('Kp', 1.0, 'Ki', 0.0, 'Kd', 0.0));

cfg.elec = struct( ...
    'fs_adc', 1000, ...
    'fs_pwm', 20000, ...
    'adc_bits', 10, ...
    'dac_bits', 10, ...
    'antiAliasFc', 50, ...
    'reconstructionFc', 50, ...
    'vmax', 12, ...
    'imax', 5);

cfg.sim = struct( ...
    'stopTime', 5.0, ...
    'fixedStep', 1e-4);

cfg.calibration = struct( ...
    'mass50g', 0.0500, ...
    'mass50p1g', 0.0501, ...
    'mass5g', 0.0050, ...
    'mass70g', 0.0700);

cfg.ui = struct( ...
    'speed', 1.0);

end
